// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: echo_errors.proto

package proto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorDetail struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Type            string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	FieldViolations []*FieldViolation      `protobuf:"bytes,2,rep,name=field_violations,json=fieldViolations,proto3" json:"field_violations,omitempty"`
	RetryDelayMs    int64                  `protobuf:"varint,3,opt,name=retry_delay_ms,json=retryDelayMs,proto3" json:"retry_delay_ms,omitempty"`
	StackEntries    []string               `protobuf:"bytes,4,rep,name=stack_entries,json=stackEntries,proto3" json:"stack_entries,omitempty"`
	DebugDetail     string                 `protobuf:"bytes,5,opt,name=debug_detail,json=debugDetail,proto3" json:"debug_detail,omitempty"`
	QuotaViolations []*QuotaViolation      `protobuf:"bytes,6,rep,name=quota_violations,json=quotaViolations,proto3" json:"quota_violations,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ErrorDetail) Reset() {
	*x = ErrorDetail{}
	mi := &file_echo_errors_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorDetail) ProtoMessage() {}

func (x *ErrorDetail) ProtoReflect() protoreflect.Message {
	mi := &file_echo_errors_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorDetail.ProtoReflect.Descriptor instead.
func (*ErrorDetail) Descriptor() ([]byte, []int) {
	return file_echo_errors_proto_rawDescGZIP(), []int{0}
}

func (x *ErrorDetail) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ErrorDetail) GetFieldViolations() []*FieldViolation {
	if x != nil {
		return x.FieldViolations
	}
	return nil
}

func (x *ErrorDetail) GetRetryDelayMs() int64 {
	if x != nil {
		return x.RetryDelayMs
	}
	return 0
}

func (x *ErrorDetail) GetStackEntries() []string {
	if x != nil {
		return x.StackEntries
	}
	return nil
}

func (x *ErrorDetail) GetDebugDetail() string {
	if x != nil {
		return x.DebugDetail
	}
	return ""
}

func (x *ErrorDetail) GetQuotaViolations() []*QuotaViolation {
	if x != nil {
		return x.QuotaViolations
	}
	return nil
}

type FieldViolation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldViolation) Reset() {
	*x = FieldViolation{}
	mi := &file_echo_errors_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldViolation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldViolation) ProtoMessage() {}

func (x *FieldViolation) ProtoReflect() protoreflect.Message {
	mi := &file_echo_errors_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldViolation.ProtoReflect.Descriptor instead.
func (*FieldViolation) Descriptor() ([]byte, []int) {
	return file_echo_errors_proto_rawDescGZIP(), []int{1}
}

func (x *FieldViolation) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *FieldViolation) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type QuotaViolation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subject       string                 `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuotaViolation) Reset() {
	*x = QuotaViolation{}
	mi := &file_echo_errors_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuotaViolation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuotaViolation) ProtoMessage() {}

func (x *QuotaViolation) ProtoReflect() protoreflect.Message {
	mi := &file_echo_errors_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuotaViolation.ProtoReflect.Descriptor instead.
func (*QuotaViolation) Descriptor() ([]byte, []int) {
	return file_echo_errors_proto_rawDescGZIP(), []int{2}
}

func (x *QuotaViolation) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *QuotaViolation) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

var File_echo_errors_proto protoreflect.FileDescriptor

const file_echo_errors_proto_rawDesc = "" +
	"\n" +
	"\x11echo_errors.proto\x12\aecho.v1\"\x97\x02\n" +
	"\vErrorDetail\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12B\n" +
	"\x10field_violations\x18\x02 \x03(\v2\x17.echo.v1.FieldViolationR\x0ffieldViolations\x12$\n" +
	"\x0eretry_delay_ms\x18\x03 \x01(\x03R\fretryDelayMs\x12#\n" +
	"\rstack_entries\x18\x04 \x03(\tR\fstackEntries\x12!\n" +
	"\fdebug_detail\x18\x05 \x01(\tR\vdebugDetail\x12B\n" +
	"\x10quota_violations\x18\x06 \x03(\v2\x17.echo.v1.QuotaViolationR\x0fquotaViolations\"H\n" +
	"\x0eFieldViolation\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"L\n" +
	"\x0eQuotaViolation\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescriptionB6Z4github.com/jsr-probitas/echo-servers/echo-grpc/protob\x06proto3"

var (
	file_echo_errors_proto_rawDescOnce sync.Once
	file_echo_errors_proto_rawDescData []byte
)

func file_echo_errors_proto_rawDescGZIP() []byte {
	file_echo_errors_proto_rawDescOnce.Do(func() {
		file_echo_errors_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_echo_errors_proto_rawDesc), len(file_echo_errors_proto_rawDesc)))
	})
	return file_echo_errors_proto_rawDescData
}

var file_echo_errors_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_echo_errors_proto_goTypes = []any{
	(*ErrorDetail)(nil),    // 0: echo.v1.ErrorDetail
	(*FieldViolation)(nil), // 1: echo.v1.FieldViolation
	(*QuotaViolation)(nil), // 2: echo.v1.QuotaViolation
}
var file_echo_errors_proto_depIdxs = []int32{
	1, // 0: echo.v1.ErrorDetail.field_violations:type_name -> echo.v1.FieldViolation
	2, // 1: echo.v1.ErrorDetail.quota_violations:type_name -> echo.v1.QuotaViolation
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_echo_errors_proto_init() }
func file_echo_errors_proto_init() {
	if File_echo_errors_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_echo_errors_proto_rawDesc), len(file_echo_errors_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_echo_errors_proto_goTypes,
		DependencyIndexes: file_echo_errors_proto_depIdxs,
		MessageInfos:      file_echo_errors_proto_msgTypes,
	}.Build()
	File_echo_errors_proto = out.File
	file_echo_errors_proto_goTypes = nil
	file_echo_errors_proto_depIdxs = nil
}
