// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: echo_deadline.proto

package proto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EchoDeadlineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EchoDeadlineRequest) Reset() {
	*x = EchoDeadlineRequest{}
	mi := &file_echo_deadline_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoDeadlineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoDeadlineRequest) ProtoMessage() {}

func (x *EchoDeadlineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_echo_deadline_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoDeadlineRequest.ProtoReflect.Descriptor instead.
func (*EchoDeadlineRequest) Descriptor() ([]byte, []int) {
	return file_echo_deadline_proto_rawDescGZIP(), []int{0}
}

func (x *EchoDeadlineRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type EchoDeadlineResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Message             string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	DeadlineRemainingMs int64                  `protobuf:"varint,2,opt,name=deadline_remaining_ms,json=deadlineRemainingMs,proto3" json:"deadline_remaining_ms,omitempty"` // -1 if no deadline set
	HasDeadline         bool                   `protobuf:"varint,3,opt,name=has_deadline,json=hasDeadline,proto3" json:"has_deadline,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *EchoDeadlineResponse) Reset() {
	*x = EchoDeadlineResponse{}
	mi := &file_echo_deadline_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoDeadlineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoDeadlineResponse) ProtoMessage() {}

func (x *EchoDeadlineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_echo_deadline_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoDeadlineResponse.ProtoReflect.Descriptor instead.
func (*EchoDeadlineResponse) Descriptor() ([]byte, []int) {
	return file_echo_deadline_proto_rawDescGZIP(), []int{1}
}

func (x *EchoDeadlineResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *EchoDeadlineResponse) GetDeadlineRemainingMs() int64 {
	if x != nil {
		return x.DeadlineRemainingMs
	}
	return 0
}

func (x *EchoDeadlineResponse) GetHasDeadline() bool {
	if x != nil {
		return x.HasDeadline
	}
	return false
}

var File_echo_deadline_proto protoreflect.FileDescriptor

const file_echo_deadline_proto_rawDesc = "" +
	"\n" +
	"\x13echo_deadline.proto\x12\aecho.v1\"/\n" +
	"\x13EchoDeadlineRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x87\x01\n" +
	"\x14EchoDeadlineResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x122\n" +
	"\x15deadline_remaining_ms\x18\x02 \x01(\x03R\x13deadlineRemainingMs\x12!\n" +
	"\fhas_deadline\x18\x03 \x01(\bR\vhasDeadlineB6Z4github.com/jsr-probitas/echo-servers/echo-grpc/protob\x06proto3"

var (
	file_echo_deadline_proto_rawDescOnce sync.Once
	file_echo_deadline_proto_rawDescData []byte
)

func file_echo_deadline_proto_rawDescGZIP() []byte {
	file_echo_deadline_proto_rawDescOnce.Do(func() {
		file_echo_deadline_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_echo_deadline_proto_rawDesc), len(file_echo_deadline_proto_rawDesc)))
	})
	return file_echo_deadline_proto_rawDescData
}

var file_echo_deadline_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_echo_deadline_proto_goTypes = []any{
	(*EchoDeadlineRequest)(nil),  // 0: echo.v1.EchoDeadlineRequest
	(*EchoDeadlineResponse)(nil), // 1: echo.v1.EchoDeadlineResponse
}
var file_echo_deadline_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_echo_deadline_proto_init() }
func file_echo_deadline_proto_init() {
	if File_echo_deadline_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_echo_deadline_proto_rawDesc), len(file_echo_deadline_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_echo_deadline_proto_goTypes,
		DependencyIndexes: file_echo_deadline_proto_depIdxs,
		MessageInfos:      file_echo_deadline_proto_msgTypes,
	}.Build()
	File_echo_deadline_proto = out.File
	file_echo_deadline_proto_goTypes = nil
	file_echo_deadline_proto_depIdxs = nil
}
