// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.32.1
// source: echo.proto

package proto

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Echo_Echo_FullMethodName                 = "/echo.v1.Echo/Echo"
	Echo_EchoWithDelay_FullMethodName        = "/echo.v1.Echo/EchoWithDelay"
	Echo_EchoError_FullMethodName            = "/echo.v1.Echo/EchoError"
	Echo_EchoRequestMetadata_FullMethodName  = "/echo.v1.Echo/EchoRequestMetadata"
	Echo_EchoWithTrailers_FullMethodName     = "/echo.v1.Echo/EchoWithTrailers"
	Echo_EchoLargePayload_FullMethodName     = "/echo.v1.Echo/EchoLargePayload"
	Echo_EchoDeadline_FullMethodName         = "/echo.v1.Echo/EchoDeadline"
	Echo_EchoErrorWithDetails_FullMethodName = "/echo.v1.Echo/EchoErrorWithDetails"
	Echo_ServerStream_FullMethodName         = "/echo.v1.Echo/ServerStream"
	Echo_ClientStream_FullMethodName         = "/echo.v1.Echo/ClientStream"
	Echo_BidirectionalStream_FullMethodName  = "/echo.v1.Echo/BidirectionalStream"
)

// EchoClient is the client API for Echo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Echo service with various RPC patterns
type EchoClient interface {
	// Unary RPCs
	Echo(ctx context.Context, in *EchoRequest, opts ...grpc.CallOption) (*EchoResponse, error)
	EchoWithDelay(ctx context.Context, in *EchoWithDelayRequest, opts ...grpc.CallOption) (*EchoResponse, error)
	EchoError(ctx context.Context, in *EchoErrorRequest, opts ...grpc.CallOption) (*EchoResponse, error)
	// Metadata/Headers RPCs
	EchoRequestMetadata(ctx context.Context, in *EchoRequestMetadataRequest, opts ...grpc.CallOption) (*EchoRequestMetadataResponse, error)
	EchoWithTrailers(ctx context.Context, in *EchoWithTrailersRequest, opts ...grpc.CallOption) (*EchoResponse, error)
	// Payload Testing RPCs
	EchoLargePayload(ctx context.Context, in *EchoLargePayloadRequest, opts ...grpc.CallOption) (*EchoLargePayloadResponse, error)
	// Deadline/Timeout RPCs
	EchoDeadline(ctx context.Context, in *EchoDeadlineRequest, opts ...grpc.CallOption) (*EchoDeadlineResponse, error)
	// Error Scenarios RPCs
	EchoErrorWithDetails(ctx context.Context, in *EchoErrorWithDetailsRequest, opts ...grpc.CallOption) (*EchoResponse, error)
	// Streaming RPCs
	ServerStream(ctx context.Context, in *ServerStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[EchoResponse], error)
	ClientStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[EchoRequest, EchoResponse], error)
	BidirectionalStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[EchoRequest, EchoResponse], error)
}

type echoClient struct {
	cc grpc.ClientConnInterface
}

func NewEchoClient(cc grpc.ClientConnInterface) EchoClient {
	return &echoClient{cc}
}

func (c *echoClient) Echo(ctx context.Context, in *EchoRequest, opts ...grpc.CallOption) (*EchoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EchoResponse)
	err := c.cc.Invoke(ctx, Echo_Echo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *echoClient) EchoWithDelay(ctx context.Context, in *EchoWithDelayRequest, opts ...grpc.CallOption) (*EchoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EchoResponse)
	err := c.cc.Invoke(ctx, Echo_EchoWithDelay_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *echoClient) EchoError(ctx context.Context, in *EchoErrorRequest, opts ...grpc.CallOption) (*EchoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EchoResponse)
	err := c.cc.Invoke(ctx, Echo_EchoError_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *echoClient) EchoRequestMetadata(ctx context.Context, in *EchoRequestMetadataRequest, opts ...grpc.CallOption) (*EchoRequestMetadataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EchoRequestMetadataResponse)
	err := c.cc.Invoke(ctx, Echo_EchoRequestMetadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *echoClient) EchoWithTrailers(ctx context.Context, in *EchoWithTrailersRequest, opts ...grpc.CallOption) (*EchoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EchoResponse)
	err := c.cc.Invoke(ctx, Echo_EchoWithTrailers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *echoClient) EchoLargePayload(ctx context.Context, in *EchoLargePayloadRequest, opts ...grpc.CallOption) (*EchoLargePayloadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EchoLargePayloadResponse)
	err := c.cc.Invoke(ctx, Echo_EchoLargePayload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *echoClient) EchoDeadline(ctx context.Context, in *EchoDeadlineRequest, opts ...grpc.CallOption) (*EchoDeadlineResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EchoDeadlineResponse)
	err := c.cc.Invoke(ctx, Echo_EchoDeadline_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *echoClient) EchoErrorWithDetails(ctx context.Context, in *EchoErrorWithDetailsRequest, opts ...grpc.CallOption) (*EchoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EchoResponse)
	err := c.cc.Invoke(ctx, Echo_EchoErrorWithDetails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *echoClient) ServerStream(ctx context.Context, in *ServerStreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[EchoResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Echo_ServiceDesc.Streams[0], Echo_ServerStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ServerStreamRequest, EchoResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Echo_ServerStreamClient = grpc.ServerStreamingClient[EchoResponse]

func (c *echoClient) ClientStream(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[EchoRequest, EchoResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Echo_ServiceDesc.Streams[1], Echo_ClientStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[EchoRequest, EchoResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Echo_ClientStreamClient = grpc.ClientStreamingClient[EchoRequest, EchoResponse]

func (c *echoClient) BidirectionalStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[EchoRequest, EchoResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Echo_ServiceDesc.Streams[2], Echo_BidirectionalStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[EchoRequest, EchoResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Echo_BidirectionalStreamClient = grpc.BidiStreamingClient[EchoRequest, EchoResponse]

// EchoServer is the server API for Echo service.
// All implementations must embed UnimplementedEchoServer
// for forward compatibility.
//
// Echo service with various RPC patterns
type EchoServer interface {
	// Unary RPCs
	Echo(context.Context, *EchoRequest) (*EchoResponse, error)
	EchoWithDelay(context.Context, *EchoWithDelayRequest) (*EchoResponse, error)
	EchoError(context.Context, *EchoErrorRequest) (*EchoResponse, error)
	// Metadata/Headers RPCs
	EchoRequestMetadata(context.Context, *EchoRequestMetadataRequest) (*EchoRequestMetadataResponse, error)
	EchoWithTrailers(context.Context, *EchoWithTrailersRequest) (*EchoResponse, error)
	// Payload Testing RPCs
	EchoLargePayload(context.Context, *EchoLargePayloadRequest) (*EchoLargePayloadResponse, error)
	// Deadline/Timeout RPCs
	EchoDeadline(context.Context, *EchoDeadlineRequest) (*EchoDeadlineResponse, error)
	// Error Scenarios RPCs
	EchoErrorWithDetails(context.Context, *EchoErrorWithDetailsRequest) (*EchoResponse, error)
	// Streaming RPCs
	ServerStream(*ServerStreamRequest, grpc.ServerStreamingServer[EchoResponse]) error
	ClientStream(grpc.ClientStreamingServer[EchoRequest, EchoResponse]) error
	BidirectionalStream(grpc.BidiStreamingServer[EchoRequest, EchoResponse]) error
	mustEmbedUnimplementedEchoServer()
}

// UnimplementedEchoServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEchoServer struct{}

func (UnimplementedEchoServer) Echo(context.Context, *EchoRequest) (*EchoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Echo not implemented")
}
func (UnimplementedEchoServer) EchoWithDelay(context.Context, *EchoWithDelayRequest) (*EchoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EchoWithDelay not implemented")
}
func (UnimplementedEchoServer) EchoError(context.Context, *EchoErrorRequest) (*EchoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EchoError not implemented")
}
func (UnimplementedEchoServer) EchoRequestMetadata(context.Context, *EchoRequestMetadataRequest) (*EchoRequestMetadataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EchoRequestMetadata not implemented")
}
func (UnimplementedEchoServer) EchoWithTrailers(context.Context, *EchoWithTrailersRequest) (*EchoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EchoWithTrailers not implemented")
}
func (UnimplementedEchoServer) EchoLargePayload(context.Context, *EchoLargePayloadRequest) (*EchoLargePayloadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EchoLargePayload not implemented")
}
func (UnimplementedEchoServer) EchoDeadline(context.Context, *EchoDeadlineRequest) (*EchoDeadlineResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EchoDeadline not implemented")
}
func (UnimplementedEchoServer) EchoErrorWithDetails(context.Context, *EchoErrorWithDetailsRequest) (*EchoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EchoErrorWithDetails not implemented")
}
func (UnimplementedEchoServer) ServerStream(*ServerStreamRequest, grpc.ServerStreamingServer[EchoResponse]) error {
	return status.Error(codes.Unimplemented, "method ServerStream not implemented")
}
func (UnimplementedEchoServer) ClientStream(grpc.ClientStreamingServer[EchoRequest, EchoResponse]) error {
	return status.Error(codes.Unimplemented, "method ClientStream not implemented")
}
func (UnimplementedEchoServer) BidirectionalStream(grpc.BidiStreamingServer[EchoRequest, EchoResponse]) error {
	return status.Error(codes.Unimplemented, "method BidirectionalStream not implemented")
}
func (UnimplementedEchoServer) mustEmbedUnimplementedEchoServer() {}
func (UnimplementedEchoServer) testEmbeddedByValue()              {}

// UnsafeEchoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EchoServer will
// result in compilation errors.
type UnsafeEchoServer interface {
	mustEmbedUnimplementedEchoServer()
}

func RegisterEchoServer(s grpc.ServiceRegistrar, srv EchoServer) {
	// If the following call panics, it indicates UnimplementedEchoServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Echo_ServiceDesc, srv)
}

func _Echo_Echo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EchoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EchoServer).Echo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Echo_Echo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EchoServer).Echo(ctx, req.(*EchoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Echo_EchoWithDelay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EchoWithDelayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EchoServer).EchoWithDelay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Echo_EchoWithDelay_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EchoServer).EchoWithDelay(ctx, req.(*EchoWithDelayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Echo_EchoError_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EchoErrorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EchoServer).EchoError(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Echo_EchoError_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EchoServer).EchoError(ctx, req.(*EchoErrorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Echo_EchoRequestMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EchoRequestMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EchoServer).EchoRequestMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Echo_EchoRequestMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EchoServer).EchoRequestMetadata(ctx, req.(*EchoRequestMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Echo_EchoWithTrailers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EchoWithTrailersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EchoServer).EchoWithTrailers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Echo_EchoWithTrailers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EchoServer).EchoWithTrailers(ctx, req.(*EchoWithTrailersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Echo_EchoLargePayload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EchoLargePayloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EchoServer).EchoLargePayload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Echo_EchoLargePayload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EchoServer).EchoLargePayload(ctx, req.(*EchoLargePayloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Echo_EchoDeadline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EchoDeadlineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EchoServer).EchoDeadline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Echo_EchoDeadline_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EchoServer).EchoDeadline(ctx, req.(*EchoDeadlineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Echo_EchoErrorWithDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EchoErrorWithDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EchoServer).EchoErrorWithDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Echo_EchoErrorWithDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EchoServer).EchoErrorWithDetails(ctx, req.(*EchoErrorWithDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Echo_ServerStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ServerStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EchoServer).ServerStream(m, &grpc.GenericServerStream[ServerStreamRequest, EchoResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Echo_ServerStreamServer = grpc.ServerStreamingServer[EchoResponse]

func _Echo_ClientStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(EchoServer).ClientStream(&grpc.GenericServerStream[EchoRequest, EchoResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Echo_ClientStreamServer = grpc.ClientStreamingServer[EchoRequest, EchoResponse]

func _Echo_BidirectionalStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(EchoServer).BidirectionalStream(&grpc.GenericServerStream[EchoRequest, EchoResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Echo_BidirectionalStreamServer = grpc.BidiStreamingServer[EchoRequest, EchoResponse]

// Echo_ServiceDesc is the grpc.ServiceDesc for Echo service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Echo_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "echo.v1.Echo",
	HandlerType: (*EchoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Echo",
			Handler:    _Echo_Echo_Handler,
		},
		{
			MethodName: "EchoWithDelay",
			Handler:    _Echo_EchoWithDelay_Handler,
		},
		{
			MethodName: "EchoError",
			Handler:    _Echo_EchoError_Handler,
		},
		{
			MethodName: "EchoRequestMetadata",
			Handler:    _Echo_EchoRequestMetadata_Handler,
		},
		{
			MethodName: "EchoWithTrailers",
			Handler:    _Echo_EchoWithTrailers_Handler,
		},
		{
			MethodName: "EchoLargePayload",
			Handler:    _Echo_EchoLargePayload_Handler,
		},
		{
			MethodName: "EchoDeadline",
			Handler:    _Echo_EchoDeadline_Handler,
		},
		{
			MethodName: "EchoErrorWithDetails",
			Handler:    _Echo_EchoErrorWithDetails_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ServerStream",
			Handler:       _Echo_ServerStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ClientStream",
			Handler:       _Echo_ClientStream_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "BidirectionalStream",
			Handler:       _Echo_BidirectionalStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "echo.proto",
}
