// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: echo_unary.proto

package proto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EchoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EchoRequest) Reset() {
	*x = EchoRequest{}
	mi := &file_echo_unary_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoRequest) ProtoMessage() {}

func (x *EchoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_echo_unary_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoRequest.ProtoReflect.Descriptor instead.
func (*EchoRequest) Descriptor() ([]byte, []int) {
	return file_echo_unary_proto_rawDescGZIP(), []int{0}
}

func (x *EchoRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type EchoWithDelayRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	DelayMs       int32                  `protobuf:"varint,2,opt,name=delay_ms,json=delayMs,proto3" json:"delay_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EchoWithDelayRequest) Reset() {
	*x = EchoWithDelayRequest{}
	mi := &file_echo_unary_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoWithDelayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoWithDelayRequest) ProtoMessage() {}

func (x *EchoWithDelayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_echo_unary_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoWithDelayRequest.ProtoReflect.Descriptor instead.
func (*EchoWithDelayRequest) Descriptor() ([]byte, []int) {
	return file_echo_unary_proto_rawDescGZIP(), []int{1}
}

func (x *EchoWithDelayRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *EchoWithDelayRequest) GetDelayMs() int32 {
	if x != nil {
		return x.DelayMs
	}
	return 0
}

type EchoErrorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Code          int32                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`      // gRPC status code (0-16)
	Details       string                 `protobuf:"bytes,3,opt,name=details,proto3" json:"details,omitempty"` // Error details message
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EchoErrorRequest) Reset() {
	*x = EchoErrorRequest{}
	mi := &file_echo_unary_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoErrorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoErrorRequest) ProtoMessage() {}

func (x *EchoErrorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_echo_unary_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoErrorRequest.ProtoReflect.Descriptor instead.
func (*EchoErrorRequest) Descriptor() ([]byte, []int) {
	return file_echo_unary_proto_rawDescGZIP(), []int{2}
}

func (x *EchoErrorRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *EchoErrorRequest) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *EchoErrorRequest) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

// EchoErrorWithDetails - Return error with rich error details (google.rpc.Status)
type EchoErrorWithDetailsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`      // gRPC status code (0-16)
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // Error message
	Details       []*ErrorDetail         `protobuf:"bytes,3,rep,name=details,proto3" json:"details,omitempty"` // Rich error details
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EchoErrorWithDetailsRequest) Reset() {
	*x = EchoErrorWithDetailsRequest{}
	mi := &file_echo_unary_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoErrorWithDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoErrorWithDetailsRequest) ProtoMessage() {}

func (x *EchoErrorWithDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_echo_unary_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoErrorWithDetailsRequest.ProtoReflect.Descriptor instead.
func (*EchoErrorWithDetailsRequest) Descriptor() ([]byte, []int) {
	return file_echo_unary_proto_rawDescGZIP(), []int{3}
}

func (x *EchoErrorWithDetailsRequest) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *EchoErrorWithDetailsRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *EchoErrorWithDetailsRequest) GetDetails() []*ErrorDetail {
	if x != nil {
		return x.Details
	}
	return nil
}

var File_echo_unary_proto protoreflect.FileDescriptor

const file_echo_unary_proto_rawDesc = "" +
	"\n" +
	"\x10echo_unary.proto\x12\aecho.v1\x1a\x11echo_errors.proto\"'\n" +
	"\vEchoRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"K\n" +
	"\x14EchoWithDelayRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x19\n" +
	"\bdelay_ms\x18\x02 \x01(\x05R\adelayMs\"Z\n" +
	"\x10EchoErrorRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x05R\x04code\x12\x18\n" +
	"\adetails\x18\x03 \x01(\tR\adetails\"{\n" +
	"\x1bEchoErrorWithDetailsRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12.\n" +
	"\adetails\x18\x03 \x03(\v2\x14.echo.v1.ErrorDetailR\adetailsB6Z4github.com/jsr-probitas/echo-servers/echo-grpc/protob\x06proto3"

var (
	file_echo_unary_proto_rawDescOnce sync.Once
	file_echo_unary_proto_rawDescData []byte
)

func file_echo_unary_proto_rawDescGZIP() []byte {
	file_echo_unary_proto_rawDescOnce.Do(func() {
		file_echo_unary_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_echo_unary_proto_rawDesc), len(file_echo_unary_proto_rawDesc)))
	})
	return file_echo_unary_proto_rawDescData
}

var file_echo_unary_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_echo_unary_proto_goTypes = []any{
	(*EchoRequest)(nil),                 // 0: echo.v1.EchoRequest
	(*EchoWithDelayRequest)(nil),        // 1: echo.v1.EchoWithDelayRequest
	(*EchoErrorRequest)(nil),            // 2: echo.v1.EchoErrorRequest
	(*EchoErrorWithDetailsRequest)(nil), // 3: echo.v1.EchoErrorWithDetailsRequest
	(*ErrorDetail)(nil),                 // 4: echo.v1.ErrorDetail
}
var file_echo_unary_proto_depIdxs = []int32{
	4, // 0: echo.v1.EchoErrorWithDetailsRequest.details:type_name -> echo.v1.ErrorDetail
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_echo_unary_proto_init() }
func file_echo_unary_proto_init() {
	if File_echo_unary_proto != nil {
		return
	}
	file_echo_errors_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_echo_unary_proto_rawDesc), len(file_echo_unary_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_echo_unary_proto_goTypes,
		DependencyIndexes: file_echo_unary_proto_depIdxs,
		MessageInfos:      file_echo_unary_proto_msgTypes,
	}.Build()
	File_echo_unary_proto = out.File
	file_echo_unary_proto_goTypes = nil
	file_echo_unary_proto_depIdxs = nil
}
