// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: echo_response.proto

package proto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EchoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Echo back request metadata
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EchoResponse) Reset() {
	*x = EchoResponse{}
	mi := &file_echo_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoResponse) ProtoMessage() {}

func (x *EchoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_echo_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoResponse.ProtoReflect.Descriptor instead.
func (*EchoResponse) Descriptor() ([]byte, []int) {
	return file_echo_response_proto_rawDescGZIP(), []int{0}
}

func (x *EchoResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *EchoResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_echo_response_proto protoreflect.FileDescriptor

const file_echo_response_proto_rawDesc = "" +
	"\n" +
	"\x13echo_response.proto\x12\aecho.v1\"\xa6\x01\n" +
	"\fEchoResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12?\n" +
	"\bmetadata\x18\x02 \x03(\v2#.echo.v1.EchoResponse.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B6Z4github.com/jsr-probitas/echo-servers/echo-grpc/protob\x06proto3"

var (
	file_echo_response_proto_rawDescOnce sync.Once
	file_echo_response_proto_rawDescData []byte
)

func file_echo_response_proto_rawDescGZIP() []byte {
	file_echo_response_proto_rawDescOnce.Do(func() {
		file_echo_response_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_echo_response_proto_rawDesc), len(file_echo_response_proto_rawDesc)))
	})
	return file_echo_response_proto_rawDescData
}

var file_echo_response_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_echo_response_proto_goTypes = []any{
	(*EchoResponse)(nil), // 0: echo.v1.EchoResponse
	nil,                  // 1: echo.v1.EchoResponse.MetadataEntry
}
var file_echo_response_proto_depIdxs = []int32{
	1, // 0: echo.v1.EchoResponse.metadata:type_name -> echo.v1.EchoResponse.MetadataEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_echo_response_proto_init() }
func file_echo_response_proto_init() {
	if File_echo_response_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_echo_response_proto_rawDesc), len(file_echo_response_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_echo_response_proto_goTypes,
		DependencyIndexes: file_echo_response_proto_depIdxs,
		MessageInfos:      file_echo_response_proto_msgTypes,
	}.Build()
	File_echo_response_proto = out.File
	file_echo_response_proto_goTypes = nil
	file_echo_response_proto_depIdxs = nil
}
