// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: echo_payload.proto

package proto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EchoLargePayloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SizeBytes     int32                  `protobuf:"varint,1,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"` // Size of payload to return (max 10MB)
	Pattern       string                 `protobuf:"bytes,2,opt,name=pattern,proto3" json:"pattern,omitempty"`                       // Optional: pattern to repeat (default: 'X')
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EchoLargePayloadRequest) Reset() {
	*x = EchoLargePayloadRequest{}
	mi := &file_echo_payload_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoLargePayloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoLargePayloadRequest) ProtoMessage() {}

func (x *EchoLargePayloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_echo_payload_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoLargePayloadRequest.ProtoReflect.Descriptor instead.
func (*EchoLargePayloadRequest) Descriptor() ([]byte, []int) {
	return file_echo_payload_proto_rawDescGZIP(), []int{0}
}

func (x *EchoLargePayloadRequest) GetSizeBytes() int32 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *EchoLargePayloadRequest) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

type EchoLargePayloadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	ActualSize    int32                  `protobuf:"varint,2,opt,name=actual_size,json=actualSize,proto3" json:"actual_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EchoLargePayloadResponse) Reset() {
	*x = EchoLargePayloadResponse{}
	mi := &file_echo_payload_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoLargePayloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoLargePayloadResponse) ProtoMessage() {}

func (x *EchoLargePayloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_echo_payload_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoLargePayloadResponse.ProtoReflect.Descriptor instead.
func (*EchoLargePayloadResponse) Descriptor() ([]byte, []int) {
	return file_echo_payload_proto_rawDescGZIP(), []int{1}
}

func (x *EchoLargePayloadResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *EchoLargePayloadResponse) GetActualSize() int32 {
	if x != nil {
		return x.ActualSize
	}
	return 0
}

var File_echo_payload_proto protoreflect.FileDescriptor

const file_echo_payload_proto_rawDesc = "" +
	"\n" +
	"\x12echo_payload.proto\x12\aecho.v1\"R\n" +
	"\x17EchoLargePayloadRequest\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x01 \x01(\x05R\tsizeBytes\x12\x18\n" +
	"\apattern\x18\x02 \x01(\tR\apattern\"U\n" +
	"\x18EchoLargePayloadResponse\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\x12\x1f\n" +
	"\vactual_size\x18\x02 \x01(\x05R\n" +
	"actualSizeB6Z4github.com/jsr-probitas/echo-servers/echo-grpc/protob\x06proto3"

var (
	file_echo_payload_proto_rawDescOnce sync.Once
	file_echo_payload_proto_rawDescData []byte
)

func file_echo_payload_proto_rawDescGZIP() []byte {
	file_echo_payload_proto_rawDescOnce.Do(func() {
		file_echo_payload_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_echo_payload_proto_rawDesc), len(file_echo_payload_proto_rawDesc)))
	})
	return file_echo_payload_proto_rawDescData
}

var file_echo_payload_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_echo_payload_proto_goTypes = []any{
	(*EchoLargePayloadRequest)(nil),  // 0: echo.v1.EchoLargePayloadRequest
	(*EchoLargePayloadResponse)(nil), // 1: echo.v1.EchoLargePayloadResponse
}
var file_echo_payload_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_echo_payload_proto_init() }
func file_echo_payload_proto_init() {
	if File_echo_payload_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_echo_payload_proto_rawDesc), len(file_echo_payload_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_echo_payload_proto_goTypes,
		DependencyIndexes: file_echo_payload_proto_depIdxs,
		MessageInfos:      file_echo_payload_proto_msgTypes,
	}.Build()
	File_echo_payload_proto = out.File
	file_echo_payload_proto_goTypes = nil
	file_echo_payload_proto_depIdxs = nil
}
