// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: echo.proto

package proto

import (
	reflect "reflect"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_echo_proto protoreflect.FileDescriptor

const file_echo_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"echo.proto\x12\aecho.v1\x1a\x13echo_deadline.proto\x1a\x13echo_metadata.proto\x1a\x12echo_payload.proto\x1a\x13echo_response.proto\x1a\x11echo_stream.proto\x1a\x10echo_unary.proto2\xb9\x06\n" +
	"\x04Echo\x123\n" +
	"\x04Echo\x12\x14.echo.v1.EchoRequest\x1a\x15.echo.v1.EchoResponse\x12E\n" +
	"\rEchoWithDelay\x12\x1d.echo.v1.EchoWithDelayRequest\x1a\x15.echo.v1.EchoResponse\x12=\n" +
	"\tEchoError\x12\x19.echo.v1.EchoErrorRequest\x1a\x15.echo.v1.EchoResponse\x12`\n" +
	"\x13EchoRequestMetadata\x12#.echo.v1.EchoRequestMetadataRequest\x1a$.echo.v1.EchoRequestMetadataResponse\x12K\n" +
	"\x10EchoWithTrailers\x12 .echo.v1.EchoWithTrailersRequest\x1a\x15.echo.v1.EchoResponse\x12W\n" +
	"\x10EchoLargePayload\x12 .echo.v1.EchoLargePayloadRequest\x1a!.echo.v1.EchoLargePayloadResponse\x12K\n" +
	"\fEchoDeadline\x12\x1c.echo.v1.EchoDeadlineRequest\x1a\x1d.echo.v1.EchoDeadlineResponse\x12S\n" +
	"\x14EchoErrorWithDetails\x12$.echo.v1.EchoErrorWithDetailsRequest\x1a\x15.echo.v1.EchoResponse\x12E\n" +
	"\fServerStream\x12\x1c.echo.v1.ServerStreamRequest\x1a\x15.echo.v1.EchoResponse0\x01\x12=\n" +
	"\fClientStream\x12\x14.echo.v1.EchoRequest\x1a\x15.echo.v1.EchoResponse(\x01\x12F\n" +
	"\x13BidirectionalStream\x12\x14.echo.v1.EchoRequest\x1a\x15.echo.v1.EchoResponse(\x010\x01B6Z4github.com/jsr-probitas/echo-servers/echo-grpc/protob\x06proto3"

var file_echo_proto_goTypes = []any{
	(*EchoRequest)(nil),                 // 0: echo.v1.EchoRequest
	(*EchoWithDelayRequest)(nil),        // 1: echo.v1.EchoWithDelayRequest
	(*EchoErrorRequest)(nil),            // 2: echo.v1.EchoErrorRequest
	(*EchoRequestMetadataRequest)(nil),  // 3: echo.v1.EchoRequestMetadataRequest
	(*EchoWithTrailersRequest)(nil),     // 4: echo.v1.EchoWithTrailersRequest
	(*EchoLargePayloadRequest)(nil),     // 5: echo.v1.EchoLargePayloadRequest
	(*EchoDeadlineRequest)(nil),         // 6: echo.v1.EchoDeadlineRequest
	(*EchoErrorWithDetailsRequest)(nil), // 7: echo.v1.EchoErrorWithDetailsRequest
	(*ServerStreamRequest)(nil),         // 8: echo.v1.ServerStreamRequest
	(*EchoResponse)(nil),                // 9: echo.v1.EchoResponse
	(*EchoRequestMetadataResponse)(nil), // 10: echo.v1.EchoRequestMetadataResponse
	(*EchoLargePayloadResponse)(nil),    // 11: echo.v1.EchoLargePayloadResponse
	(*EchoDeadlineResponse)(nil),        // 12: echo.v1.EchoDeadlineResponse
}
var file_echo_proto_depIdxs = []int32{
	0,  // 0: echo.v1.Echo.Echo:input_type -> echo.v1.EchoRequest
	1,  // 1: echo.v1.Echo.EchoWithDelay:input_type -> echo.v1.EchoWithDelayRequest
	2,  // 2: echo.v1.Echo.EchoError:input_type -> echo.v1.EchoErrorRequest
	3,  // 3: echo.v1.Echo.EchoRequestMetadata:input_type -> echo.v1.EchoRequestMetadataRequest
	4,  // 4: echo.v1.Echo.EchoWithTrailers:input_type -> echo.v1.EchoWithTrailersRequest
	5,  // 5: echo.v1.Echo.EchoLargePayload:input_type -> echo.v1.EchoLargePayloadRequest
	6,  // 6: echo.v1.Echo.EchoDeadline:input_type -> echo.v1.EchoDeadlineRequest
	7,  // 7: echo.v1.Echo.EchoErrorWithDetails:input_type -> echo.v1.EchoErrorWithDetailsRequest
	8,  // 8: echo.v1.Echo.ServerStream:input_type -> echo.v1.ServerStreamRequest
	0,  // 9: echo.v1.Echo.ClientStream:input_type -> echo.v1.EchoRequest
	0,  // 10: echo.v1.Echo.BidirectionalStream:input_type -> echo.v1.EchoRequest
	9,  // 11: echo.v1.Echo.Echo:output_type -> echo.v1.EchoResponse
	9,  // 12: echo.v1.Echo.EchoWithDelay:output_type -> echo.v1.EchoResponse
	9,  // 13: echo.v1.Echo.EchoError:output_type -> echo.v1.EchoResponse
	10, // 14: echo.v1.Echo.EchoRequestMetadata:output_type -> echo.v1.EchoRequestMetadataResponse
	9,  // 15: echo.v1.Echo.EchoWithTrailers:output_type -> echo.v1.EchoResponse
	11, // 16: echo.v1.Echo.EchoLargePayload:output_type -> echo.v1.EchoLargePayloadResponse
	12, // 17: echo.v1.Echo.EchoDeadline:output_type -> echo.v1.EchoDeadlineResponse
	9,  // 18: echo.v1.Echo.EchoErrorWithDetails:output_type -> echo.v1.EchoResponse
	9,  // 19: echo.v1.Echo.ServerStream:output_type -> echo.v1.EchoResponse
	9,  // 20: echo.v1.Echo.ClientStream:output_type -> echo.v1.EchoResponse
	9,  // 21: echo.v1.Echo.BidirectionalStream:output_type -> echo.v1.EchoResponse
	11, // [11:22] is the sub-list for method output_type
	0,  // [0:11] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_echo_proto_init() }
func file_echo_proto_init() {
	if File_echo_proto != nil {
		return
	}
	file_echo_deadline_proto_init()
	file_echo_metadata_proto_init()
	file_echo_payload_proto_init()
	file_echo_response_proto_init()
	file_echo_stream_proto_init()
	file_echo_unary_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_echo_proto_rawDesc), len(file_echo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_echo_proto_goTypes,
		DependencyIndexes: file_echo_proto_depIdxs,
	}.Build()
	File_echo_proto = out.File
	file_echo_proto_goTypes = nil
	file_echo_proto_depIdxs = nil
}
