// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: echo_metadata.proto

package proto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MetadataValues struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []string               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetadataValues) Reset() {
	*x = MetadataValues{}
	mi := &file_echo_metadata_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataValues) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataValues) ProtoMessage() {}

func (x *MetadataValues) ProtoReflect() protoreflect.Message {
	mi := &file_echo_metadata_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataValues.ProtoReflect.Descriptor instead.
func (*MetadataValues) Descriptor() ([]byte, []int) {
	return file_echo_metadata_proto_rawDescGZIP(), []int{0}
}

func (x *MetadataValues) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type EchoRequestMetadataRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional: filter to specific metadata keys (empty = return all)
	Keys          []string `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EchoRequestMetadataRequest) Reset() {
	*x = EchoRequestMetadataRequest{}
	mi := &file_echo_metadata_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoRequestMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoRequestMetadataRequest) ProtoMessage() {}

func (x *EchoRequestMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_echo_metadata_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoRequestMetadataRequest.ProtoReflect.Descriptor instead.
func (*EchoRequestMetadataRequest) Descriptor() ([]byte, []int) {
	return file_echo_metadata_proto_rawDescGZIP(), []int{1}
}

func (x *EchoRequestMetadataRequest) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

type EchoRequestMetadataResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// All request metadata as key-value pairs
	Metadata      map[string]*MetadataValues `protobuf:"bytes,1,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EchoRequestMetadataResponse) Reset() {
	*x = EchoRequestMetadataResponse{}
	mi := &file_echo_metadata_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoRequestMetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoRequestMetadataResponse) ProtoMessage() {}

func (x *EchoRequestMetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_echo_metadata_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoRequestMetadataResponse.ProtoReflect.Descriptor instead.
func (*EchoRequestMetadataResponse) Descriptor() ([]byte, []int) {
	return file_echo_metadata_proto_rawDescGZIP(), []int{2}
}

func (x *EchoRequestMetadataResponse) GetMetadata() map[string]*MetadataValues {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// EchoWithTrailers - Return response with trailing metadata
type EchoWithTrailersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Trailers      map[string]string      `protobuf:"bytes,2,rep,name=trailers,proto3" json:"trailers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Trailers to send with response
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EchoWithTrailersRequest) Reset() {
	*x = EchoWithTrailersRequest{}
	mi := &file_echo_metadata_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoWithTrailersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoWithTrailersRequest) ProtoMessage() {}

func (x *EchoWithTrailersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_echo_metadata_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoWithTrailersRequest.ProtoReflect.Descriptor instead.
func (*EchoWithTrailersRequest) Descriptor() ([]byte, []int) {
	return file_echo_metadata_proto_rawDescGZIP(), []int{3}
}

func (x *EchoWithTrailersRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *EchoWithTrailersRequest) GetTrailers() map[string]string {
	if x != nil {
		return x.Trailers
	}
	return nil
}

var File_echo_metadata_proto protoreflect.FileDescriptor

const file_echo_metadata_proto_rawDesc = "" +
	"\n" +
	"\x13echo_metadata.proto\x12\aecho.v1\"(\n" +
	"\x0eMetadataValues\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06values\"0\n" +
	"\x1aEchoRequestMetadataRequest\x12\x12\n" +
	"\x04keys\x18\x01 \x03(\tR\x04keys\"\xc3\x01\n" +
	"\x1bEchoRequestMetadataResponse\x12N\n" +
	"\bmetadata\x18\x01 \x03(\v22.echo.v1.EchoRequestMetadataResponse.MetadataEntryR\bmetadata\x1aT\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12-\n" +
	"\x05value\x18\x02 \x01(\v2\x17.echo.v1.MetadataValuesR\x05value:\x028\x01\"\xbc\x01\n" +
	"\x17EchoWithTrailersRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12J\n" +
	"\btrailers\x18\x02 \x03(\v2..echo.v1.EchoWithTrailersRequest.TrailersEntryR\btrailers\x1a;\n" +
	"\rTrailersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B6Z4github.com/jsr-probitas/echo-servers/echo-grpc/protob\x06proto3"

var (
	file_echo_metadata_proto_rawDescOnce sync.Once
	file_echo_metadata_proto_rawDescData []byte
)

func file_echo_metadata_proto_rawDescGZIP() []byte {
	file_echo_metadata_proto_rawDescOnce.Do(func() {
		file_echo_metadata_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_echo_metadata_proto_rawDesc), len(file_echo_metadata_proto_rawDesc)))
	})
	return file_echo_metadata_proto_rawDescData
}

var file_echo_metadata_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_echo_metadata_proto_goTypes = []any{
	(*MetadataValues)(nil),              // 0: echo.v1.MetadataValues
	(*EchoRequestMetadataRequest)(nil),  // 1: echo.v1.EchoRequestMetadataRequest
	(*EchoRequestMetadataResponse)(nil), // 2: echo.v1.EchoRequestMetadataResponse
	(*EchoWithTrailersRequest)(nil),     // 3: echo.v1.EchoWithTrailersRequest
	nil,                                 // 4: echo.v1.EchoRequestMetadataResponse.MetadataEntry
	nil,                                 // 5: echo.v1.EchoWithTrailersRequest.TrailersEntry
}
var file_echo_metadata_proto_depIdxs = []int32{
	4, // 0: echo.v1.EchoRequestMetadataResponse.metadata:type_name -> echo.v1.EchoRequestMetadataResponse.MetadataEntry
	5, // 1: echo.v1.EchoWithTrailersRequest.trailers:type_name -> echo.v1.EchoWithTrailersRequest.TrailersEntry
	0, // 2: echo.v1.EchoRequestMetadataResponse.MetadataEntry.value:type_name -> echo.v1.MetadataValues
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_echo_metadata_proto_init() }
func file_echo_metadata_proto_init() {
	if File_echo_metadata_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_echo_metadata_proto_rawDesc), len(file_echo_metadata_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_echo_metadata_proto_goTypes,
		DependencyIndexes: file_echo_metadata_proto_depIdxs,
		MessageInfos:      file_echo_metadata_proto_msgTypes,
	}.Build()
	File_echo_metadata_proto = out.File
	file_echo_metadata_proto_goTypes = nil
	file_echo_metadata_proto_depIdxs = nil
}
