// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: echo_stream.proto

package proto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServerStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`                             // Number of responses to stream
	IntervalMs    int32                  `protobuf:"varint,3,opt,name=interval_ms,json=intervalMs,proto3" json:"interval_ms,omitempty"` // Interval between responses
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerStreamRequest) Reset() {
	*x = ServerStreamRequest{}
	mi := &file_echo_stream_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerStreamRequest) ProtoMessage() {}

func (x *ServerStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_echo_stream_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerStreamRequest.ProtoReflect.Descriptor instead.
func (*ServerStreamRequest) Descriptor() ([]byte, []int) {
	return file_echo_stream_proto_rawDescGZIP(), []int{0}
}

func (x *ServerStreamRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ServerStreamRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ServerStreamRequest) GetIntervalMs() int32 {
	if x != nil {
		return x.IntervalMs
	}
	return 0
}

var File_echo_stream_proto protoreflect.FileDescriptor

const file_echo_stream_proto_rawDesc = "" +
	"\n" +
	"\x11echo_stream.proto\x12\aecho.v1\"f\n" +
	"\x13ServerStreamRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\x12\x1f\n" +
	"\vinterval_ms\x18\x03 \x01(\x05R\n" +
	"intervalMsB6Z4github.com/jsr-probitas/echo-servers/echo-grpc/protob\x06proto3"

var (
	file_echo_stream_proto_rawDescOnce sync.Once
	file_echo_stream_proto_rawDescData []byte
)

func file_echo_stream_proto_rawDescGZIP() []byte {
	file_echo_stream_proto_rawDescOnce.Do(func() {
		file_echo_stream_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_echo_stream_proto_rawDesc), len(file_echo_stream_proto_rawDesc)))
	})
	return file_echo_stream_proto_rawDescData
}

var file_echo_stream_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_echo_stream_proto_goTypes = []any{
	(*ServerStreamRequest)(nil), // 0: echo.v1.ServerStreamRequest
}
var file_echo_stream_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_echo_stream_proto_init() }
func file_echo_stream_proto_init() {
	if File_echo_stream_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_echo_stream_proto_rawDesc), len(file_echo_stream_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_echo_stream_proto_goTypes,
		DependencyIndexes: file_echo_stream_proto_depIdxs,
		MessageInfos:      file_echo_stream_proto_msgTypes,
	}.Build()
	File_echo_stream_proto = out.File
	file_echo_stream_proto_goTypes = nil
	file_echo_stream_proto_depIdxs = nil
}
