// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: echo.proto

package protoconnect

import (
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"

	connect "connectrpc.com/connect"
	proto "github.com/jsr-probitas/echo-servers/echo-connectrpc/proto"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// EchoName is the fully-qualified name of the Echo service.
	EchoName = "echo.v1.Echo"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// EchoEchoProcedure is the fully-qualified name of the Echo's Echo RPC.
	EchoEchoProcedure = "/echo.v1.Echo/Echo"
	// EchoEchoWithDelayProcedure is the fully-qualified name of the Echo's EchoWithDelay RPC.
	EchoEchoWithDelayProcedure = "/echo.v1.Echo/EchoWithDelay"
	// EchoEchoErrorProcedure is the fully-qualified name of the Echo's EchoError RPC.
	EchoEchoErrorProcedure = "/echo.v1.Echo/EchoError"
	// EchoEchoRequestMetadataProcedure is the fully-qualified name of the Echo's EchoRequestMetadata
	// RPC.
	EchoEchoRequestMetadataProcedure = "/echo.v1.Echo/EchoRequestMetadata"
	// EchoEchoWithTrailersProcedure is the fully-qualified name of the Echo's EchoWithTrailers RPC.
	EchoEchoWithTrailersProcedure = "/echo.v1.Echo/EchoWithTrailers"
	// EchoEchoLargePayloadProcedure is the fully-qualified name of the Echo's EchoLargePayload RPC.
	EchoEchoLargePayloadProcedure = "/echo.v1.Echo/EchoLargePayload"
	// EchoEchoDeadlineProcedure is the fully-qualified name of the Echo's EchoDeadline RPC.
	EchoEchoDeadlineProcedure = "/echo.v1.Echo/EchoDeadline"
	// EchoEchoErrorWithDetailsProcedure is the fully-qualified name of the Echo's EchoErrorWithDetails
	// RPC.
	EchoEchoErrorWithDetailsProcedure = "/echo.v1.Echo/EchoErrorWithDetails"
	// EchoServerStreamProcedure is the fully-qualified name of the Echo's ServerStream RPC.
	EchoServerStreamProcedure = "/echo.v1.Echo/ServerStream"
	// EchoClientStreamProcedure is the fully-qualified name of the Echo's ClientStream RPC.
	EchoClientStreamProcedure = "/echo.v1.Echo/ClientStream"
	// EchoBidirectionalStreamProcedure is the fully-qualified name of the Echo's BidirectionalStream
	// RPC.
	EchoBidirectionalStreamProcedure = "/echo.v1.Echo/BidirectionalStream"
)

// EchoClient is a client for the echo.v1.Echo service.
type EchoClient interface {
	// Unary RPCs
	Echo(context.Context, *connect.Request[proto.EchoRequest]) (*connect.Response[proto.EchoResponse], error)
	EchoWithDelay(context.Context, *connect.Request[proto.EchoWithDelayRequest]) (*connect.Response[proto.EchoResponse], error)
	EchoError(context.Context, *connect.Request[proto.EchoErrorRequest]) (*connect.Response[proto.EchoResponse], error)
	// Metadata/Headers RPCs
	EchoRequestMetadata(context.Context, *connect.Request[proto.EchoRequestMetadataRequest]) (*connect.Response[proto.EchoRequestMetadataResponse], error)
	EchoWithTrailers(context.Context, *connect.Request[proto.EchoWithTrailersRequest]) (*connect.Response[proto.EchoResponse], error)
	// Payload Testing RPCs
	EchoLargePayload(context.Context, *connect.Request[proto.EchoLargePayloadRequest]) (*connect.Response[proto.EchoLargePayloadResponse], error)
	// Deadline/Timeout RPCs
	EchoDeadline(context.Context, *connect.Request[proto.EchoDeadlineRequest]) (*connect.Response[proto.EchoDeadlineResponse], error)
	// Error Scenarios RPCs
	EchoErrorWithDetails(context.Context, *connect.Request[proto.EchoErrorWithDetailsRequest]) (*connect.Response[proto.EchoResponse], error)
	// Streaming RPCs
	ServerStream(context.Context, *connect.Request[proto.ServerStreamRequest]) (*connect.ServerStreamForClient[proto.EchoResponse], error)
	ClientStream(context.Context) *connect.ClientStreamForClient[proto.EchoRequest, proto.EchoResponse]
	BidirectionalStream(context.Context) *connect.BidiStreamForClient[proto.EchoRequest, proto.EchoResponse]
}

// NewEchoClient constructs a client for the echo.v1.Echo service. By default, it uses the Connect
// protocol with the binary Protobuf Codec, asks for gzipped responses, and sends uncompressed
// requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewEchoClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) EchoClient {
	baseURL = strings.TrimRight(baseURL, "/")
	echoMethods := proto.File_echo_proto.Services().ByName("Echo").Methods()
	return &echoClient{
		echo: connect.NewClient[proto.EchoRequest, proto.EchoResponse](
			httpClient,
			baseURL+EchoEchoProcedure,
			connect.WithSchema(echoMethods.ByName("Echo")),
			connect.WithClientOptions(opts...),
		),
		echoWithDelay: connect.NewClient[proto.EchoWithDelayRequest, proto.EchoResponse](
			httpClient,
			baseURL+EchoEchoWithDelayProcedure,
			connect.WithSchema(echoMethods.ByName("EchoWithDelay")),
			connect.WithClientOptions(opts...),
		),
		echoError: connect.NewClient[proto.EchoErrorRequest, proto.EchoResponse](
			httpClient,
			baseURL+EchoEchoErrorProcedure,
			connect.WithSchema(echoMethods.ByName("EchoError")),
			connect.WithClientOptions(opts...),
		),
		echoRequestMetadata: connect.NewClient[proto.EchoRequestMetadataRequest, proto.EchoRequestMetadataResponse](
			httpClient,
			baseURL+EchoEchoRequestMetadataProcedure,
			connect.WithSchema(echoMethods.ByName("EchoRequestMetadata")),
			connect.WithClientOptions(opts...),
		),
		echoWithTrailers: connect.NewClient[proto.EchoWithTrailersRequest, proto.EchoResponse](
			httpClient,
			baseURL+EchoEchoWithTrailersProcedure,
			connect.WithSchema(echoMethods.ByName("EchoWithTrailers")),
			connect.WithClientOptions(opts...),
		),
		echoLargePayload: connect.NewClient[proto.EchoLargePayloadRequest, proto.EchoLargePayloadResponse](
			httpClient,
			baseURL+EchoEchoLargePayloadProcedure,
			connect.WithSchema(echoMethods.ByName("EchoLargePayload")),
			connect.WithClientOptions(opts...),
		),
		echoDeadline: connect.NewClient[proto.EchoDeadlineRequest, proto.EchoDeadlineResponse](
			httpClient,
			baseURL+EchoEchoDeadlineProcedure,
			connect.WithSchema(echoMethods.ByName("EchoDeadline")),
			connect.WithClientOptions(opts...),
		),
		echoErrorWithDetails: connect.NewClient[proto.EchoErrorWithDetailsRequest, proto.EchoResponse](
			httpClient,
			baseURL+EchoEchoErrorWithDetailsProcedure,
			connect.WithSchema(echoMethods.ByName("EchoErrorWithDetails")),
			connect.WithClientOptions(opts...),
		),
		serverStream: connect.NewClient[proto.ServerStreamRequest, proto.EchoResponse](
			httpClient,
			baseURL+EchoServerStreamProcedure,
			connect.WithSchema(echoMethods.ByName("ServerStream")),
			connect.WithClientOptions(opts...),
		),
		clientStream: connect.NewClient[proto.EchoRequest, proto.EchoResponse](
			httpClient,
			baseURL+EchoClientStreamProcedure,
			connect.WithSchema(echoMethods.ByName("ClientStream")),
			connect.WithClientOptions(opts...),
		),
		bidirectionalStream: connect.NewClient[proto.EchoRequest, proto.EchoResponse](
			httpClient,
			baseURL+EchoBidirectionalStreamProcedure,
			connect.WithSchema(echoMethods.ByName("BidirectionalStream")),
			connect.WithClientOptions(opts...),
		),
	}
}

// echoClient implements EchoClient.
type echoClient struct {
	echo                 *connect.Client[proto.EchoRequest, proto.EchoResponse]
	echoWithDelay        *connect.Client[proto.EchoWithDelayRequest, proto.EchoResponse]
	echoError            *connect.Client[proto.EchoErrorRequest, proto.EchoResponse]
	echoRequestMetadata  *connect.Client[proto.EchoRequestMetadataRequest, proto.EchoRequestMetadataResponse]
	echoWithTrailers     *connect.Client[proto.EchoWithTrailersRequest, proto.EchoResponse]
	echoLargePayload     *connect.Client[proto.EchoLargePayloadRequest, proto.EchoLargePayloadResponse]
	echoDeadline         *connect.Client[proto.EchoDeadlineRequest, proto.EchoDeadlineResponse]
	echoErrorWithDetails *connect.Client[proto.EchoErrorWithDetailsRequest, proto.EchoResponse]
	serverStream         *connect.Client[proto.ServerStreamRequest, proto.EchoResponse]
	clientStream         *connect.Client[proto.EchoRequest, proto.EchoResponse]
	bidirectionalStream  *connect.Client[proto.EchoRequest, proto.EchoResponse]
}

// Echo calls echo.v1.Echo.Echo.
func (c *echoClient) Echo(ctx context.Context, req *connect.Request[proto.EchoRequest]) (*connect.Response[proto.EchoResponse], error) {
	return c.echo.CallUnary(ctx, req)
}

// EchoWithDelay calls echo.v1.Echo.EchoWithDelay.
func (c *echoClient) EchoWithDelay(ctx context.Context, req *connect.Request[proto.EchoWithDelayRequest]) (*connect.Response[proto.EchoResponse], error) {
	return c.echoWithDelay.CallUnary(ctx, req)
}

// EchoError calls echo.v1.Echo.EchoError.
func (c *echoClient) EchoError(ctx context.Context, req *connect.Request[proto.EchoErrorRequest]) (*connect.Response[proto.EchoResponse], error) {
	return c.echoError.CallUnary(ctx, req)
}

// EchoRequestMetadata calls echo.v1.Echo.EchoRequestMetadata.
func (c *echoClient) EchoRequestMetadata(ctx context.Context, req *connect.Request[proto.EchoRequestMetadataRequest]) (*connect.Response[proto.EchoRequestMetadataResponse], error) {
	return c.echoRequestMetadata.CallUnary(ctx, req)
}

// EchoWithTrailers calls echo.v1.Echo.EchoWithTrailers.
func (c *echoClient) EchoWithTrailers(ctx context.Context, req *connect.Request[proto.EchoWithTrailersRequest]) (*connect.Response[proto.EchoResponse], error) {
	return c.echoWithTrailers.CallUnary(ctx, req)
}

// EchoLargePayload calls echo.v1.Echo.EchoLargePayload.
func (c *echoClient) EchoLargePayload(ctx context.Context, req *connect.Request[proto.EchoLargePayloadRequest]) (*connect.Response[proto.EchoLargePayloadResponse], error) {
	return c.echoLargePayload.CallUnary(ctx, req)
}

// EchoDeadline calls echo.v1.Echo.EchoDeadline.
func (c *echoClient) EchoDeadline(ctx context.Context, req *connect.Request[proto.EchoDeadlineRequest]) (*connect.Response[proto.EchoDeadlineResponse], error) {
	return c.echoDeadline.CallUnary(ctx, req)
}

// EchoErrorWithDetails calls echo.v1.Echo.EchoErrorWithDetails.
func (c *echoClient) EchoErrorWithDetails(ctx context.Context, req *connect.Request[proto.EchoErrorWithDetailsRequest]) (*connect.Response[proto.EchoResponse], error) {
	return c.echoErrorWithDetails.CallUnary(ctx, req)
}

// ServerStream calls echo.v1.Echo.ServerStream.
func (c *echoClient) ServerStream(ctx context.Context, req *connect.Request[proto.ServerStreamRequest]) (*connect.ServerStreamForClient[proto.EchoResponse], error) {
	return c.serverStream.CallServerStream(ctx, req)
}

// ClientStream calls echo.v1.Echo.ClientStream.
func (c *echoClient) ClientStream(ctx context.Context) *connect.ClientStreamForClient[proto.EchoRequest, proto.EchoResponse] {
	return c.clientStream.CallClientStream(ctx)
}

// BidirectionalStream calls echo.v1.Echo.BidirectionalStream.
func (c *echoClient) BidirectionalStream(ctx context.Context) *connect.BidiStreamForClient[proto.EchoRequest, proto.EchoResponse] {
	return c.bidirectionalStream.CallBidiStream(ctx)
}

// EchoHandler is an implementation of the echo.v1.Echo service.
type EchoHandler interface {
	// Unary RPCs
	Echo(context.Context, *connect.Request[proto.EchoRequest]) (*connect.Response[proto.EchoResponse], error)
	EchoWithDelay(context.Context, *connect.Request[proto.EchoWithDelayRequest]) (*connect.Response[proto.EchoResponse], error)
	EchoError(context.Context, *connect.Request[proto.EchoErrorRequest]) (*connect.Response[proto.EchoResponse], error)
	// Metadata/Headers RPCs
	EchoRequestMetadata(context.Context, *connect.Request[proto.EchoRequestMetadataRequest]) (*connect.Response[proto.EchoRequestMetadataResponse], error)
	EchoWithTrailers(context.Context, *connect.Request[proto.EchoWithTrailersRequest]) (*connect.Response[proto.EchoResponse], error)
	// Payload Testing RPCs
	EchoLargePayload(context.Context, *connect.Request[proto.EchoLargePayloadRequest]) (*connect.Response[proto.EchoLargePayloadResponse], error)
	// Deadline/Timeout RPCs
	EchoDeadline(context.Context, *connect.Request[proto.EchoDeadlineRequest]) (*connect.Response[proto.EchoDeadlineResponse], error)
	// Error Scenarios RPCs
	EchoErrorWithDetails(context.Context, *connect.Request[proto.EchoErrorWithDetailsRequest]) (*connect.Response[proto.EchoResponse], error)
	// Streaming RPCs
	ServerStream(context.Context, *connect.Request[proto.ServerStreamRequest], *connect.ServerStream[proto.EchoResponse]) error
	ClientStream(context.Context, *connect.ClientStream[proto.EchoRequest]) (*connect.Response[proto.EchoResponse], error)
	BidirectionalStream(context.Context, *connect.BidiStream[proto.EchoRequest, proto.EchoResponse]) error
}

// NewEchoHandler builds an HTTP handler from the service implementation. It returns the path on
// which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewEchoHandler(svc EchoHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	echoMethods := proto.File_echo_proto.Services().ByName("Echo").Methods()
	echoEchoHandler := connect.NewUnaryHandler(
		EchoEchoProcedure,
		svc.Echo,
		connect.WithSchema(echoMethods.ByName("Echo")),
		connect.WithHandlerOptions(opts...),
	)
	echoEchoWithDelayHandler := connect.NewUnaryHandler(
		EchoEchoWithDelayProcedure,
		svc.EchoWithDelay,
		connect.WithSchema(echoMethods.ByName("EchoWithDelay")),
		connect.WithHandlerOptions(opts...),
	)
	echoEchoErrorHandler := connect.NewUnaryHandler(
		EchoEchoErrorProcedure,
		svc.EchoError,
		connect.WithSchema(echoMethods.ByName("EchoError")),
		connect.WithHandlerOptions(opts...),
	)
	echoEchoRequestMetadataHandler := connect.NewUnaryHandler(
		EchoEchoRequestMetadataProcedure,
		svc.EchoRequestMetadata,
		connect.WithSchema(echoMethods.ByName("EchoRequestMetadata")),
		connect.WithHandlerOptions(opts...),
	)
	echoEchoWithTrailersHandler := connect.NewUnaryHandler(
		EchoEchoWithTrailersProcedure,
		svc.EchoWithTrailers,
		connect.WithSchema(echoMethods.ByName("EchoWithTrailers")),
		connect.WithHandlerOptions(opts...),
	)
	echoEchoLargePayloadHandler := connect.NewUnaryHandler(
		EchoEchoLargePayloadProcedure,
		svc.EchoLargePayload,
		connect.WithSchema(echoMethods.ByName("EchoLargePayload")),
		connect.WithHandlerOptions(opts...),
	)
	echoEchoDeadlineHandler := connect.NewUnaryHandler(
		EchoEchoDeadlineProcedure,
		svc.EchoDeadline,
		connect.WithSchema(echoMethods.ByName("EchoDeadline")),
		connect.WithHandlerOptions(opts...),
	)
	echoEchoErrorWithDetailsHandler := connect.NewUnaryHandler(
		EchoEchoErrorWithDetailsProcedure,
		svc.EchoErrorWithDetails,
		connect.WithSchema(echoMethods.ByName("EchoErrorWithDetails")),
		connect.WithHandlerOptions(opts...),
	)
	echoServerStreamHandler := connect.NewServerStreamHandler(
		EchoServerStreamProcedure,
		svc.ServerStream,
		connect.WithSchema(echoMethods.ByName("ServerStream")),
		connect.WithHandlerOptions(opts...),
	)
	echoClientStreamHandler := connect.NewClientStreamHandler(
		EchoClientStreamProcedure,
		svc.ClientStream,
		connect.WithSchema(echoMethods.ByName("ClientStream")),
		connect.WithHandlerOptions(opts...),
	)
	echoBidirectionalStreamHandler := connect.NewBidiStreamHandler(
		EchoBidirectionalStreamProcedure,
		svc.BidirectionalStream,
		connect.WithSchema(echoMethods.ByName("BidirectionalStream")),
		connect.WithHandlerOptions(opts...),
	)
	return "/echo.v1.Echo/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case EchoEchoProcedure:
			echoEchoHandler.ServeHTTP(w, r)
		case EchoEchoWithDelayProcedure:
			echoEchoWithDelayHandler.ServeHTTP(w, r)
		case EchoEchoErrorProcedure:
			echoEchoErrorHandler.ServeHTTP(w, r)
		case EchoEchoRequestMetadataProcedure:
			echoEchoRequestMetadataHandler.ServeHTTP(w, r)
		case EchoEchoWithTrailersProcedure:
			echoEchoWithTrailersHandler.ServeHTTP(w, r)
		case EchoEchoLargePayloadProcedure:
			echoEchoLargePayloadHandler.ServeHTTP(w, r)
		case EchoEchoDeadlineProcedure:
			echoEchoDeadlineHandler.ServeHTTP(w, r)
		case EchoEchoErrorWithDetailsProcedure:
			echoEchoErrorWithDetailsHandler.ServeHTTP(w, r)
		case EchoServerStreamProcedure:
			echoServerStreamHandler.ServeHTTP(w, r)
		case EchoClientStreamProcedure:
			echoClientStreamHandler.ServeHTTP(w, r)
		case EchoBidirectionalStreamProcedure:
			echoBidirectionalStreamHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedEchoHandler returns CodeUnimplemented from all methods.
type UnimplementedEchoHandler struct{}

func (UnimplementedEchoHandler) Echo(context.Context, *connect.Request[proto.EchoRequest]) (*connect.Response[proto.EchoResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("echo.v1.Echo.Echo is not implemented"))
}

func (UnimplementedEchoHandler) EchoWithDelay(context.Context, *connect.Request[proto.EchoWithDelayRequest]) (*connect.Response[proto.EchoResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("echo.v1.Echo.EchoWithDelay is not implemented"))
}

func (UnimplementedEchoHandler) EchoError(context.Context, *connect.Request[proto.EchoErrorRequest]) (*connect.Response[proto.EchoResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("echo.v1.Echo.EchoError is not implemented"))
}

func (UnimplementedEchoHandler) EchoRequestMetadata(context.Context, *connect.Request[proto.EchoRequestMetadataRequest]) (*connect.Response[proto.EchoRequestMetadataResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("echo.v1.Echo.EchoRequestMetadata is not implemented"))
}

func (UnimplementedEchoHandler) EchoWithTrailers(context.Context, *connect.Request[proto.EchoWithTrailersRequest]) (*connect.Response[proto.EchoResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("echo.v1.Echo.EchoWithTrailers is not implemented"))
}

func (UnimplementedEchoHandler) EchoLargePayload(context.Context, *connect.Request[proto.EchoLargePayloadRequest]) (*connect.Response[proto.EchoLargePayloadResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("echo.v1.Echo.EchoLargePayload is not implemented"))
}

func (UnimplementedEchoHandler) EchoDeadline(context.Context, *connect.Request[proto.EchoDeadlineRequest]) (*connect.Response[proto.EchoDeadlineResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("echo.v1.Echo.EchoDeadline is not implemented"))
}

func (UnimplementedEchoHandler) EchoErrorWithDetails(context.Context, *connect.Request[proto.EchoErrorWithDetailsRequest]) (*connect.Response[proto.EchoResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("echo.v1.Echo.EchoErrorWithDetails is not implemented"))
}

func (UnimplementedEchoHandler) ServerStream(context.Context, *connect.Request[proto.ServerStreamRequest], *connect.ServerStream[proto.EchoResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("echo.v1.Echo.ServerStream is not implemented"))
}

func (UnimplementedEchoHandler) ClientStream(context.Context, *connect.ClientStream[proto.EchoRequest]) (*connect.Response[proto.EchoResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("echo.v1.Echo.ClientStream is not implemented"))
}

func (UnimplementedEchoHandler) BidirectionalStream(context.Context, *connect.BidiStream[proto.EchoRequest, proto.EchoResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("echo.v1.Echo.BidirectionalStream is not implemented"))
}
